// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsyahdtqanimigragwpk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzeWFoZHRxYW5pbWlncmFnd3BrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMzU1NDAsImV4cCI6MjA1OTgxMTU0MH0.fAxe4X48p3TmMCwcblSHzWd7WGHfKE7mzn2l09yGbqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);